### PR TITLE
Redesign the CairoSurface type

### LINKED ISSUE #248: segmentation fault
With Cairo 0.5.4, Julia 0.7.0:

```
julia> using Cairo

julia> CairoSVGSurface(IOBuffer(), 200, 110)
CairoSurface{UInt32}(Ptr{Nothing} @0x00007f8373b0e020, 200.0, 110.0, #undef)

julia> CairoContext(ans)
CairoContext(Ptr{Nothing} @0x00007f8371a68400, CairoSurface{UInt32}(Ptr{Nothing} @0x00007f8373b0e020, 200.0, 110.0, #undef), Ptr{Nothing} @0x00007f8370ca4820)

julia> GC.gc()

julia> GC.gc()

signal (11): Segmentation fault: 11
in expression starting at no file:0
jl_array_grow_at_end at /Users/osx/buildbot/slave/package_osx64/build/src/array.c:824
resize! at ./array.jl:814 [inlined]
ensureroom at ./iobuffer.jl:298
unsafe_write at ./iobuffer.jl:387
unsafe_write at ./io.jl:512 [inlined]
write_to_stream_callback at /Users/ajkeller/.julia/packages/Cairo/blE1h/src/Cairo.jl:141
unknown function (ip: 0x11756bdb9)
_cairo_output_stream_vprintf at /Users/ajkeller/.julia/packages/Homebrew/l8kUw/deps/usr/lib/libcairo.dylib (unknown line)
_cairo_output_stream_printf at /Users/ajkeller/.julia/packages/Homebrew/l8kUw/deps/usr/lib/libcairo.dylib (unknown line)
_cairo_svg_document_finish at /Users/ajkeller/.julia/packages/Homebrew/l8kUw/deps/usr/lib/libcairo.dylib (unknown line)
_cairo_svg_surface_finish at /Users/ajkeller/.julia/packages/Homebrew/l8kUw/deps/usr/lib/libcairo.dylib (unknown line)
_cairo_surface_finish at /Users/ajkeller/.julia/packages/Homebrew/l8kUw/deps/usr/lib/libcairo.dylib (unknown line)
cairo_surface_finish at /Users/ajkeller/.julia/packages/Homebrew/l8kUw/deps/usr/lib/libcairo.dylib (unknown line)
_cairo_paginated_surface_finish at /Users/ajkeller/.julia/packages/Homebrew/l8kUw/deps/usr/lib/libcairo.dylib (unknown line)
_cairo_surface_finish at /Users/ajkeller/.julia/packages/Homebrew/l8kUw/deps/usr/lib/libcairo.dylib (unknown line)
cairo_surface_destroy at /Users/ajkeller/.julia/packages/Homebrew/l8kUw/deps/usr/lib/libcairo.dylib (unknown line)
destroy at /Users/ajkeller/.julia/packages/Cairo/blE1h/src/Cairo.jl:197
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1829
jl_apply at /Users/osx/buildbot/slave/package_osx64/build/src/./julia.h:1538 [inlined]
run_finalizer at /Users/osx/buildbot/slave/package_osx64/build/src/gc.c:115
jl_gc_run_finalizers_in_list at /Users/osx/buildbot/slave/package_osx64/build/src/gc.c:210
run_finalizers at /Users/osx/buildbot/slave/package_osx64/build/src/gc.c:245 [inlined]
jl_gc_collect at /Users/osx/buildbot/slave/package_osx64/build/src/gc.c:2652
gc at ./gcutils.jl:56 [inlined]
gc at ./gcutils.jl:56
do_call at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:324
eval_stmt_value at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:363 [inlined]
eval_body at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:686
jl_interpret_toplevel_thunk_callback at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:799
unknown function (ip: 0xfffffffffffffffe)
unknown function (ip: 0x10a32f2ff)
unknown function (ip: 0x0)
jl_interpret_toplevel_thunk at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:808
jl_toplevel_eval_flex at /Users/osx/buildbot/slave/package_osx64/build/src/toplevel.c:831
jl_toplevel_eval_in at /Users/osx/buildbot/slave/package_osx64/build/src/builtins.c:633
eval at ./boot.jl:319 [inlined]
#25 at /Users/ajkeller/.julia/packages/Atom/jJn7Y/src/repl.jl:125 [inlined]
with_logstate at ./logging.jl:397
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1829
with_logger at ./logging.jl:493
top-level scope at /Users/ajkeller/.julia/packages/Atom/jJn7Y/src/repl.jl:124
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1829
jl_toplevel_eval_flex at /Users/osx/buildbot/slave/package_osx64/build/src/toplevel.c:825
jl_toplevel_eval_in at /Users/osx/buildbot/slave/package_osx64/build/src/builtins.c:633
eval at ./boot.jl:319
eval_user_input at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v0.7/REPL/src/REPL.jl:85
macro expansion at /Users/ajkeller/.julia/packages/Revise/aU3Za/src/Revise.jl:764 [inlined]
#41 at ./task.jl:262
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1829
jl_apply at /Users/osx/buildbot/slave/package_osx64/build/src/./julia.h:1538 [inlined]
start_task at /Users/osx/buildbot/slave/package_osx64/build/src/task.c:268
Allocations: 33522189 (Pool: 33515188; Big: 7001); GC: 76

Julia has exited. Press Enter to start a new session.
```

Occasionally I've seen Julia survive and give an error like:
```
error in running finalizer: ArgumentError(msg="ensureroom failed, IOBuffer is not writeable")
```

### PR DESCRIPTION
**Pull request by tknopp**
This fixes #248 by holding a reference to the IO stream in the `CairoSurface` type. I made `CairoSurface` abstract and introduced three concrete types: `CairoSurfaceBase`. `CairoSurfaceImage` and `CairoSurfaceIOStream` since they hold different things and encoding this all into a single type gets a mess.

### CODE REVIEW

**Comment by tknopp** [comment]
@tkelman: It would be great if you could review this PR. If you look at this function:
```
function CairoSVGSurface(stream::T, w::Real, h::Real) where {T<:IO}
    callback = get_stream_callback(T)
    ptr = ccall((:cairo_svg_surface_create_for_stream,_jl_libcairo), Ptr{Nothing},
                (Ptr{Nothing}, Any, Float64, Float64), callback, stream, w, h)
    CairoSurface(ptr, w, h)
end

```
we do not hold a reference on the `stream`. Therefore the garbage collector will collect it later although the `CairoSurface` object is still alive. Is that analysis correct? If yes: My PR fixes this by keeping a reference on `stream`.

**Comment by lobingera** [comment]
On a first glance this looks good to me, does it solve the finalizer issue?

**Comment by tknopp** [comment]
yes
```
julia> using Cairo
julia> CairoSVGSurface(IOBuffer(), 200, 110)
Cairo.CairoSurfaceIOStream{UInt32}(Ptr{Nothing} @0x00007fd2e44a63c0, 200.0, 110.0, IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=false, size=0, maxsize=Inf, ptr=1, mark=-1))
julia> GC.gc()
julia> GC.gc()
julia> GC.gc()
julia> 
```

feel free to merge.

**Comment by lobingera** [comment]
I'll look later today, a test doing exactly this would be nice, but for testing i need a clear indication that GC.gc() works like that the same in REPL and compiled code.

**Comment by tknopp** [comment]
I added a test that fails with a segfault on master.

**Comment by tkelman** [comment]
master should be tagged with the bindeps change before this gets merged
________________________________

**Comment by lobingera** [comment]
@tkelman Which BinDeps change?

**Comment by tkelman** [comment]
re-enabling the source build that was too-hastily commented out and released without review
________________________________

**Comment by lobingera** [comment]
@tkelman I see. But the complaints about this "source build" missing are rather sparse, while homebrew and WinRPM (and Libcurl and Libexpat) issues dominate the discussion. I'm not feeling fine to do a release now, as it raises the expectation of improvement - which it does for linux source builds.
If you really see the need, feel free to do it, you have Owner rights on this org.

**Comment by tkelman** [comment]
That means nobody on a non-Debian, non-Fedora, non-opensuse linux distribution (or one of those distros but not having root permissions) has tried to install Cairo within the last 6 days on either Julia 0.6 or 1.0 and filed a github issue about it. Mac and Windows are more common than those distros but they do exist and they would be broken right now, which is a regression relative to 0.5.3 and all prior releases. I'm not actively using or maintaining this package or the language it's written in, but I can tell you what's broken.

**Comment by lobingera** [comment]
Hmm.

File: src/Cairo.jl [hunk 1]
```diff
@@ -1,4 +1,4 @@
-VERSION < v"0.7.0-beta2.199" && __precompile__()
```
Comment (tkelman) [inline src/Cairo.jl]: why are you disabling precompilation on 0.6?

Comment (lobingera) [reply src/Cairo.jl]: It doesn't look like my idea ...

Comment (lobingera) [reply src/Cairo.jl]: I deleted the release and i will look at this again tomorrow morning (my time).

Comment (tknopp) [reply src/Cairo.jl]: Believe me or not but I have no idea why I removed that. Maybe I hit `dd` too hastily in vim. But it was certainly not my intention.

**Comment by tkelman** [comment]
It would have been very straightforward to do 0.7-specific work in a way that didn't introduce regressions for stable users on 0.6. Just keep in mind that the more of a hurry you do things in, the more likely you are to make mistakes.

**Comment by lobingera** [comment]
@tkelman I support your position on backwards compatibility and not breaking things for stable users. In my day job (as i share the engineering background with you) i try hard very hard to make tooling working and running with previous versions of the framework (matlab, we supported recently >matlabR2007a ...). In julia development the main stream is "move fast and break things" and backward compatibility is not supported in all places. See Compat, see current state of BinDeps vs. BinDeps2 and other places. See f.e. that Tobias' changes here are based on the 'new' cfunction style which seems to have been put into julia without much testing and no consistent story line how to change. All this makes supporting >0.6 and 0.6 at the same time actually NOT very straight forward and i'm thankful to Tobias to do the changes i didn't have time to.

**Comment by timholy** [comment]
Now that julia 0.7 is here (and we're not worried anymore about supporting a moving target), the easiest way to support 0.7+ and 0.6 without breakage is to have separate versions of the package: 0.6 users get to install Cairo up through `v"0.n.x"` whereas 0.7+ users get to install `v"0.n+1.0"` and higher. The `0.n` series is just what always worked on 0.6; all new development happens on the `0.n+1` version. Yes, this means 0.6 users miss out on all the awesome new features, but that's just the price of safety.

If you have a big enough problem on your hands (I haven't looked at all) then you can always retroactively set the bounds in METADATA on older releases of Cairo.

Nice to "see" you, @tkelman! We thought fondly of you at JuliaCon2018, and hope to see you again sometime soon. All my best!

**Comment by tkelman** [comment]
this particular package has had some unfortinate bindeps problems inflicted from non julia sources on win32 and mac even on 0.6, so "always worked" is a bit optimistic.

there are a few packages I still happen to be in the "watching" state on, this is one of them. otherwise I'm unlikely to be participating in the julia ecosystem. happy to entertain anyone over a coffee or beer why that is, to the extent that I don't violate any NDAs.

**Comment by tknopp** [comment]
So there is @lobingera @timholy @davidanthoff  that are currently caring about Cairo.jl. I know of @davidanthoff and @timholy that they support dropping 0.6 on master which will free us from making mistakes braking 0.6. If you all three agree I would prepare a 0.7/1.0 release that includes this fix here. I would make a branch `release-julia-0.6` before that, so that we can potentially back port things. Does this have your support?

Back to topic. @timholy If you have 5 minutes of time you could have a look at my question in 
https://github.com/JuliaGraphics/Cairo.jl/pull/249#issuecomment-414639329 so that I know that my analysis and my fix was sound.

**Comment by timholy** [comment]
Technically, since the stream is an input to that function it could be held by the caller. Nevertheless if the surface relies on the stream for its functionality, I agree, it's better to hold a reference to it. :+1:

**Comment by tknopp** [comment]
Ok thanks. I just wanted to hear that my analysis is correct. I will then merge this once the 0.5.5 release is in METADATA. If there are no objections then I will update REQUIRE to 0.7.

**Comment by lobingera** [comment]
I object.

**Comment by tknopp** [comment]
ok fine, then carry maintaining 0.6 compatibility.

**Comment by lobingera** [comment]
@tknopp Regarding your comment about changing the structure, well if it passes all tests it should be OK. I don't think people worked with the structure (note to myself: check local packages ...)
